// Stripe product/price mapping for subscription tiers
export const SUBSCRIPTION_TIERS = {
  free: {
    name: "Free",
    tagline: "Écoutez, votez, découvrez",
    price: 0,
    price_id: null,
    product_id: null,
    features: [
      "Écouter toutes les soumissions",
      "5 votes par semaine",
      "Accès au classement en direct",
      "Découvrir tous les artistes",
      "Profil basique",
    ],
    highlights: [
      { label: "Votes", value: "5 / semaine" },
      { label: "Soumission", value: "Non" },
      { label: "Commentaires", value: "Non" },
      { label: "Profil artiste", value: "Basique" },
      { label: "Statistiques", value: "Non" },
      { label: "Outils IA", value: "Non" },
    ],
    limits: {
      votes_per_week: 5,
      can_submit: false,
      analytics: false,
      ai_feedback: false,
      marketing_kit: false,
      comments_per_week: 0,
    },
  },
  pro: {
    name: "Pro",
    tagline: "Soumettez, progressez, brillez",
    price: 9.99,
    price_id: "price_1SxwC0DFa5Y9NR1IzyElGuxb",
    product_id: "prod_TvnnCLdThflvd5",
    features: [
      "Soumettre 1 morceau par semaine",
      "Votes illimités",
      "5 commentaires par semaine sur les votes",
      "Profil artiste personnalisé (avatar, liens sociaux)",
      "Statistiques de votes sur votre profil",
      "Résumé IA des votes reçus",
      "Recommandations IA personnalisées",
      "Chatbot assistant musical IA",
      "Écoute, classement et découverte inclus",
    ],
    highlights: [
      { label: "Votes", value: "Illimités" },
      { label: "Soumission", value: "1 / semaine" },
      { label: "Commentaires", value: "5 / semaine" },
      { label: "Profil artiste", value: "Personnalisé" },
      { label: "Statistiques", value: "Oui" },
      { label: "Outils IA", value: "3 outils" },
    ],
    limits: {
      votes_per_week: Infinity,
      can_submit: true,
      analytics: true,
      ai_feedback: false,
      marketing_kit: false,
      comments_per_week: 5,
    },
  },
  elite: {
    name: "Elite",
    tagline: "L'expérience complète, sans limites",
    price: 19.99,
    price_id: "price_1SxwC1DFa5Y9NR1I0VRck1kX",
    product_id: "prod_Tvnn1RBP7qVms7",
    features: [
      "Soumettre 1 morceau par semaine",
      "Votes et commentaires illimités",
      "Feedback IA structuré (analyse détaillée)",
      "Résumé IA des votes reçus",
      "Recommandations IA personnalisées",
      "Chatbot assistant musical IA",
      "Profil artiste premium (avatar, banner, liens sociaux)",
      "Badge Elite sur le profil",
      "Statistiques de votes détaillées",
    ],
    highlights: [
      { label: "Votes", value: "Illimités" },
      { label: "Soumission", value: "1 / semaine" },
      { label: "Commentaires", value: "Illimités" },
      { label: "Profil artiste", value: "Premium + badge" },
      { label: "Statistiques", value: "Détaillées" },
      { label: "Outils IA", value: "4 outils (+ feedback)" },
    ],
    limits: {
      votes_per_week: Infinity,
      can_submit: true,
      analytics: true,
      ai_feedback: true,
      marketing_kit: false,
      comments_per_week: Infinity,
    },
  },
} as const;

export type SubscriptionTier = keyof typeof SUBSCRIPTION_TIERS;
