// Stripe product/price mapping for subscription tiers
export const SUBSCRIPTION_TIERS = {
  free: {
    name: "Free",
    tagline: "pricing.freeTagline",
    price: 0,
    price_id: null,
    product_id: null,
    featureKeys: [
      "pricing.freeFeature1",
      "pricing.freeFeature2",
      "pricing.freeFeature3",
      "pricing.freeFeature4",
      "pricing.freeFeature5",
    ],
    highlightKeys: [
      { labelKey: "pricing.highlightVotes", valueKey: "pricing.fivePerWeek" },
      { labelKey: "pricing.highlightSubmission", valueKey: "pricing.no" },
      { labelKey: "pricing.highlightComments", valueKey: "pricing.no" },
      { labelKey: "pricing.highlightProfile", valueKey: "pricing.highlightBasic" },
      { labelKey: "pricing.highlightStats", valueKey: "pricing.no" },
      { labelKey: "pricing.highlightAI", valueKey: "pricing.no" },
    ],
    limits: {
      votes_per_week: 5,
      can_submit: false,
      analytics: false,
      ai_feedback: false,
      marketing_kit: false,
      comments_per_week: 0,
    },
  },
  pro: {
    name: "Pro",
    tagline: "pricing.proTagline",
    price: 9.99,
    price_id: "price_1T8k86DFa5Y9NR1IPzfZhZrx",
    product_id: "prod_U6y4cllNm98nSu",
    featureKeys: [
      "pricing.proFeature1",
      "pricing.proFeature2",
      "pricing.proFeature3",
      "pricing.proFeature4",
      "pricing.proFeature5",
      "pricing.proFeature6",
      "pricing.proFeature7",
      "pricing.proFeature8",
      "pricing.proFeature9",
    ],
    highlightKeys: [
      { labelKey: "pricing.highlightVotes", valueKey: "pricing.unlimited" },
      { labelKey: "pricing.highlightSubmission", valueKey: "pricing.onePerWeek" },
      { labelKey: "pricing.highlightComments", valueKey: "pricing.fivePerWeek" },
      { labelKey: "pricing.highlightProfile", valueKey: "pricing.highlightCustom" },
      { labelKey: "pricing.highlightStats", valueKey: "pricing.unlimited" },
      { labelKey: "pricing.highlightAI", valueKey: "pricing.highlight3tools" },
    ],
    limits: {
      votes_per_week: Infinity,
      can_submit: true,
      analytics: true,
      ai_feedback: false,
      marketing_kit: false,
      comments_per_week: 5,
    },
  },
  elite: {
    name: "Elite",
    tagline: "pricing.eliteTagline",
    price: 19.99,
    price_id: "price_1SxwC1DFa5Y9NR1I0VRck1kX",
    product_id: "prod_Tvnn1RBP7qVms7",
    featureKeys: [
      "pricing.eliteFeature1",
      "pricing.eliteFeature2",
      "pricing.eliteFeature3",
      "pricing.eliteFeature4",
      "pricing.eliteFeature5",
      "pricing.eliteFeature6",
      "pricing.eliteFeature7",
      "pricing.eliteFeature8",
      "pricing.eliteFeature9",
    ],
    highlightKeys: [
      { labelKey: "pricing.highlightVotes", valueKey: "pricing.unlimited" },
      { labelKey: "pricing.highlightSubmission", valueKey: "pricing.onePerWeek" },
      { labelKey: "pricing.highlightComments", valueKey: "pricing.unlimited" },
      { labelKey: "pricing.highlightProfile", valueKey: "pricing.premiumBadge" },
      { labelKey: "pricing.highlightStats", valueKey: "pricing.detailed" },
      { labelKey: "pricing.highlightAI", valueKey: "pricing.highlight4tools" },
    ],
    limits: {
      votes_per_week: Infinity,
      can_submit: true,
      analytics: true,
      ai_feedback: true,
      marketing_kit: false,
      comments_per_week: Infinity,
    },
  },
} as const;

export type SubscriptionTier = keyof typeof SUBSCRIPTION_TIERS;
